#NAME OM SINGH,ADMISSION NUMBER 23SCSE1430328
#QUESTION NUMBER-15
#PYTHON PROGRAM TO DISPLAY THE ALL INTEGERS WITHIN THE RANGE 100 TO 200 WHOSE SUM OF DIGITS IS AN EVEN NUMBER.
for i in range(100,201):
    if sum(int(digit) for digit in str(i))%2==0:
        print(i)